// https://orm.drizzle.team/docs/rls#using-with-supabase  (re-exported roles, authUsers, authUid, realtimeMessages)
import { getColumnTable, getTableName, sql } from "drizzle-orm"
import {
  type AnyPgColumn,
  bigint,
  type ExtraConfigColumn,
  type HasIdentity,
  integer,
  type PgBigInt53Builder,
  type PgBigInt64Builder,
  type PgIntegerBuilder,
  type PgPolicyConfig,
  type PgUUIDBuilder,
  pgPolicy,
  type SetHasDefault,
  type SetIsPrimaryKey,
  timestamp,
  uuid,
  varchar,
} from "drizzle-orm/pg-core"
import { snakeCase } from "drizzle-orm/pg-core/casing"
import { authenticatedRole, authUid, authUsers } from "drizzle-orm/supabase"

// pg-core primitives without the `pg` prefix they repeat at every call site.
// `table` is missing on purpose. Zeno's own is at the bottom of this file.
// biome-ignore lint/performance/noBarrelFile: intentional public re-export surface
export {
  isPgEnum as isEnum,
  isPgMaterializedView as isMaterializedView,
  isPgSchema as isSchema,
  isPgSequence as isSequence,
  isPgView as isView,
  pgEnum as enum,
  pgMaterializedView as materializedView,
  pgPolicy as policy,
  pgRole as role,
  pgSchema as schema,
  pgSequence as sequence,
  pgTableCreator as tableCreator,
  pgView as view,
} from "drizzle-orm/pg-core"

// Supabase roles, auth.users and SQL helpers, re-exported so a schema file
// imports everything it needs from here.
export {
  anonRole,
  authenticatedRole,
  authUid,
  authUsers,
  postgresRole,
  realtimeMessages,
  realtimeTopic,
  serviceRole,
  supabaseAuthAdminRole,
} from "drizzle-orm/supabase"

// Call and spread into a column map. Every audit mixin here is a factory rather
// than a shared object, because Drizzle's builder methods mutate `this` and
// return it. One builder in two tables would leak `.notNull()`, `.references()`
// and its name from whichever table customised it first.
export const timestamps = () => ({
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
})

export const authUserId = (name?: string) =>
  uuid(name)
    .notNull()
    .references(() => authUsers.id)

export const createdBy = () => authUserId("created_by").default(authUid)
export const updatedBy = () =>
  authUserId("updated_by")
    .default(authUid)
    .$onUpdate(() => authUid)

export const authorship = () => ({
  createdBy: createdBy(),
  updatedBy: updatedBy(),
})

export const auditColumns = () => ({
  ...timestamps(),
  ...authorship(),
})

const DEFAULT_ID_NAME = "id"

// `[T] extends [U]` blocks distribution, so a plain `boolean` gives one column
// type rather than a union of both.
type UuidPrimaryIdColumn<TDefaultRandom extends boolean> = [
  TDefaultRandom,
] extends [false]
  ? SetIsPrimaryKey<PgUUIDBuilder>
  : SetHasDefault<SetIsPrimaryKey<PgUUIDBuilder>>

// `defaultRandom: false` when the id comes from elsewhere. A mirror of
// auth.users takes its id from the referenced row, and skipping the default
// also makes the column required on insert.
export function uuidPrimaryId<TDefaultRandom extends boolean = true>(options?: {
  name?: string
  defaultRandom?: TDefaultRandom
}): UuidPrimaryIdColumn<TDefaultRandom>
export function uuidPrimaryId(
  options: { name?: string; defaultRandom?: boolean } = {}
) {
  const { name = DEFAULT_ID_NAME, defaultRandom = true } = options
  const column = uuid(name).primaryKey()

  return defaultRandom ? column.defaultRandom() : column
}

type IdentityType = "integer" | "bigint"
type IdentityMode = "number" | "bigint"
type IdentityGeneration = "byDefault" | "always"

type IdentityBuilder<
  TType extends IdentityType,
  TMode extends IdentityMode,
> = TType extends "integer"
  ? PgIntegerBuilder
  : TMode extends "bigint"
    ? PgBigInt64Builder
    : PgBigInt53Builder

type SequentialPrimaryIdColumn<
  TType extends IdentityType,
  TMode extends IdentityMode,
  TGeneration extends IdentityGeneration,
> = HasIdentity<SetIsPrimaryKey<IdentityBuilder<TType, TMode>>, TGeneration>

// Defaults match the Supabase table editor: bigint, generated by default as
// identity. Option names follow Postgres, which calls this an identity column.
// `mode` is "number" because PostgREST serialises to JSON numbers.
export function sequentialPrimaryId<
  TType extends IdentityType = "bigint",
  TMode extends IdentityMode = "number",
  TGeneration extends IdentityGeneration = "byDefault",
>(
  options: {
    name?: string
    type?: TType
    // `never` for integer, which has one JavaScript representation.
    mode?: TType extends "integer" ? never : TMode
    generated?: TGeneration
  } = {}
): SequentialPrimaryIdColumn<TType, TMode, TGeneration> {
  const {
    name = DEFAULT_ID_NAME,
    type = "bigint",
    mode = "number",
    generated = "byDefault",
  } = options as {
    name?: string
    type?: IdentityType
    mode?: IdentityMode
    generated?: IdentityGeneration
  }
  const column =
    type === "integer"
      ? integer(name).primaryKey()
      : bigint(name, { mode }).primaryKey()

  // TypeScript can't follow the runtime branch. A single cast is rejected too,
  // because Drizzle types `$default` off a polymorphic `this`, which leaves the
  // concrete builders unassignable to the intersected return type.
  return (generated === "always"
    ? column.generatedAlwaysAsIdentity()
    : column.generatedByDefaultAsIdentity()) as unknown as SequentialPrimaryIdColumn<
    TType,
    TMode,
    TGeneration
  >
}

export const assignedPrimaryId = ({
  name = DEFAULT_ID_NAME,
  length,
}: {
  name?: string
  length?: number
} = {}) => varchar(name, { length }).primaryKey()

type PrimaryIdKind = "uuid" | "sequential" | "assigned"

type PrimaryIdColumn<TKind extends PrimaryIdKind> = TKind extends "uuid"
  ? UuidPrimaryIdColumn<true>
  : TKind extends "sequential"
    ? SequentialPrimaryIdColumn<"bigint", "number", "byDefault">
    : ReturnType<typeof assignedPrimaryId>

// Takes the kind and nothing else, so it can't regrow the overload set it
// replaced. Renaming a column or changing how the value is generated goes
// through the helper behind the kind. "sequential" is the default because it is
// the id the Supabase table editor gives a new table.
export function primaryId<TKind extends PrimaryIdKind = "sequential">(
  kind?: TKind
): PrimaryIdColumn<TKind>
export function primaryId(kind: PrimaryIdKind = "sequential") {
  if (kind === "uuid") {
    return uuidPrimaryId()
  }

  if (kind === "assigned") {
    return assignedPrimaryId()
  }

  return sequentialPrimaryId()
}

type PolicyOptions = Omit<PgPolicyConfig, "for">
type PolicyOperation = NonNullable<PgPolicyConfig["for"]>
type AuthenticatedPolicyOptions = Omit<PgPolicyConfig, "for" | "to">

function operationPolicy(
  name: string,
  operation: PolicyOperation,
  config: PolicyOptions = {}
) {
  return pgPolicy(name, { ...config, for: operation })
}

export const selectPolicy = (name: string, config: PolicyOptions = {}) =>
  operationPolicy(name, "select", config)

export const insertPolicy = (name: string, config: PolicyOptions = {}) =>
  operationPolicy(name, "insert", config)

export const updatePolicy = (name: string, config: PolicyOptions = {}) =>
  operationPolicy(name, "update", config)

export const deletePolicy = (name: string, config: PolicyOptions = {}) =>
  operationPolicy(name, "delete", config)

export const allPolicy = (name: string, config: PolicyOptions = {}) =>
  operationPolicy(name, "all", config)

// `to: authenticatedRole` on its own, which every hand-written policy repeats.
// The condition stays yours, unlike the owner helpers below.
export const authenticatedSelectPolicy = (
  name: string,
  config: AuthenticatedPolicyOptions = {}
) => selectPolicy(name, { ...config, to: authenticatedRole })

export const authenticatedInsertPolicy = (
  name: string,
  config: AuthenticatedPolicyOptions = {}
) => insertPolicy(name, { ...config, to: authenticatedRole })

export const authenticatedUpdatePolicy = (
  name: string,
  config: AuthenticatedPolicyOptions = {}
) => updatePolicy(name, { ...config, to: authenticatedRole })

export const authenticatedDeletePolicy = (
  name: string,
  config: AuthenticatedPolicyOptions = {}
) => deletePolicy(name, { ...config, to: authenticatedRole })

export const authenticatedAllPolicy = (
  name: string,
  config: AuthenticatedPolicyOptions = {}
) => allPolicy(name, { ...config, to: authenticatedRole })

// Postgres takes the condition in a different clause per operation: `using`
// filters the rows already there, `withCheck` vets the rows going in.
const POLICY_CLAUSES = {
  all: ["using", "withCheck"],
  delete: ["using"],
  insert: ["withCheck"],
  select: ["using"],
  update: ["using", "withCheck"],
} as const satisfies Record<PolicyOperation, readonly ("using" | "withCheck")[]>

const POLICY_BUILDERS = {
  all: allPolicy,
  delete: deletePolicy,
  insert: insertPolicy,
  select: selectPolicy,
  update: updatePolicy,
} as const satisfies Record<PolicyOperation, typeof selectPolicy>

const FUNCTION_POLICY_OPERATIONS = [
  "select",
  "insert",
  "update",
  "delete",
] as const

type FunctionPoliciesOptions = {
  /** Passed to each function, e.g. the row's id. Omit for a function that takes none. */
  argument?: AnyPgColumn
  /** Prefix for the default function and policy names. Default `"can"`. */
  prefix?: string
  /** Overrides the generated policy name. */
  name?: (operation: PolicyOperation, table: string) => string
}

// The columns object drizzle hands the extra-config callback. Taking it rather
// than the table is what keeps `functionPolicies` usable: naming the table
// inside its own definition makes its type circular, so `(t) => ...` is the
// only reference available at that point.
type ExtraConfigColumns = Record<string, ExtraConfigColumn>

/**
 * One policy per operation, each delegating to a `security definer` function.
 *
 * Access rarely depends only on the row's own owner column, and the usual
 * answer is a function, which is also the standard advice for keeping RLS
 * predicates out of the planner's way:
 *
 * ```ts
 * table("posts", { id: primaryId("uuid") }, (t) =>
 *   functionPolicies(t, { argument: t.id })
 * )
 * ```
 *
 * ```sql
 * CREATE POLICY "can_select_posts" ON "posts" FOR SELECT TO "authenticated"
 *   USING ((select "can_select_posts"("posts"."id")));
 * ```
 */
export const functionPolicies = (
  columns: ExtraConfigColumns,
  { argument, name, prefix = "can" }: FunctionPoliciesOptions = {}
) => {
  const [firstColumn] = Object.values(columns)

  if (!firstColumn) {
    throw new Error("functionPolicies needs a table with at least one column")
  }

  const tableName = getTableName(getColumnTable(firstColumn))

  return FUNCTION_POLICY_OPERATIONS.map((operation) => {
    const functionName = `${prefix}_${operation}_${tableName}`
    // `select` wraps it so Postgres evaluates the call once per statement
    // rather than once per row, the same shape `authUid` uses.
    const condition = argument
      ? sql`(select ${sql.identifier(functionName)}(${argument}))`
      : sql`(select ${sql.identifier(functionName)}())`
    const clauses = POLICY_CLAUSES[operation]

    return POLICY_BUILDERS[operation](
      name?.(operation, tableName) ?? functionName,
      {
        to: authenticatedRole,
        ...Object.fromEntries(clauses.map((clause) => [clause, condition])),
      }
    )
  })
}

export const authUserOwns = (ownerColumn: AnyPgColumn) =>
  sql`${ownerColumn} = ${authUid}`

type OwnerPolicyOptions = Omit<PgPolicyConfig, "for" | "to">

export const authenticatedOwnerSelectPolicy = (
  name: string,
  ownerColumn: AnyPgColumn,
  config: OwnerPolicyOptions = {}
) =>
  selectPolicy(name, {
    ...config,
    to: authenticatedRole,
    using: config.using ?? authUserOwns(ownerColumn),
  })

export const authenticatedOwnerInsertPolicy = (
  name: string,
  ownerColumn: AnyPgColumn,
  config: OwnerPolicyOptions = {}
) =>
  insertPolicy(name, {
    ...config,
    to: authenticatedRole,
    withCheck: config.withCheck ?? authUserOwns(ownerColumn),
  })

export const authenticatedOwnerUpdatePolicy = (
  name: string,
  ownerColumn: AnyPgColumn,
  config: OwnerPolicyOptions = {}
) => {
  const ownerCondition = authUserOwns(ownerColumn)
  return updatePolicy(name, {
    ...config,
    to: authenticatedRole,
    using: config.using ?? ownerCondition,
    withCheck: config.withCheck ?? ownerCondition,
  })
}

export const authenticatedOwnerDeletePolicy = (
  name: string,
  ownerColumn: AnyPgColumn,
  config: OwnerPolicyOptions = {}
) =>
  deletePolicy(name, {
    ...config,
    to: authenticatedRole,
    using: config.using ?? authUserOwns(ownerColumn),
  })

export const authenticatedOwnerAllPolicy = (
  name: string,
  ownerColumn: AnyPgColumn,
  config: OwnerPolicyOptions = {}
) => {
  const ownerCondition = authUserOwns(ownerColumn)
  return allPolicy(name, {
    ...config,
    to: authenticatedRole,
    using: config.using ?? ownerCondition,
    withCheck: config.withCheck ?? ownerCondition,
  })
}

// Application-owned tables. Column keys stay camelCase, database identifiers
// become snake_case, and RLS is on.
export const table = snakeCase.table.withRLS

// Escape hatch for intentionally non-RLS tables such as seed/reference data.
export const unsecureTable = snakeCase.table
